preferences:
  autowire-on-sync-mode: UPDATE_OPTIONAL_DEPENDENCIES
  repositories-mode: FAIL_ON_PROJECT_REPOS

repositories:
  gradle-plugin-portal:
    scope: PLUGINS
  google:
  maven-central:
  maven-local:

plugins:
  org.jetbrains.kotlin.multiplatform:
    alias: kotlin-multiplatform
    version: 2.1.10
  org.jetbrains.kotlin.android:
    alias: kotlin-android
    version-ref: kotlin-multiplatform
  org.jetbrains.compose:
    alias: jetbrains-compose
    version: 1.8.2
  org.jetbrains.kotlin.plugin.compose:
    alias: compose-compiler
    version-ref: kotlin-multiplatform
  com.android.application:
    alias: android-application
    version: 8.9.3
  com.android.library:
    alias: android-library
    version-ref: android-application
  org.jetbrains.dokka:
    alias: kotlin-dokka
    version: 1.9.20
    auto-update: false
  com.vanniktech.maven.publish:
    alias: maven-publish
    version: 0.34.0

libraries:
  com.highcapable.kavaref:
    kavaref-core:
      version: 1.0.1
    kavaref-extension:
      version: 1.0.1
  androidx.core:
    core-ktx:
      version: 1.17.0
  androidx.fragment:
    fragment-ktx:
      version: 1.8.9
  androidx.activity:
    activity:
      version: 1.10.1
  androidx.appcompat:
    appcompat:
      version: 1.7.1
  androidx.recyclerview:
    recyclerview:
      version: 1.4.0
  androidx.viewpager:
    viewpager:
      version: 1.1.0
  androidx.viewpager2:
    viewpager2:
      version: 1.1.0
  com.google.android.material:
    material:
      # Workaround for a bug in version 1.12.0
      version: 1.11.0
      auto-update: false
  androidx.constraintlayout:
    constraintlayout:
      version: 2.2.1
  androidx.test.ext:
    junit:
      version: 1.3.0
  androidx.test.espresso:
    espresso-core:
      version: 3.7.0
  junit:
    junit:
      version: 4.13.2